/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-12-17 05:14:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reservationAgreePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635990617507L));
    _jspx_dependants.put("jar:file:/C:/CamFlexProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CamFlex/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>예약 결제 및 약관 동의</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/include/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/include/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"col-sm-12\">\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<h2>예약 내용 확인</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"well\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><font size=\"4\">객실 정보 : 객실 이름, 예약 일자</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><font size=\"4\">예약자 정보 : 회원 정보</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div class=\"col-sm-12\">\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<h2>이용약관 동의</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("			<div class=\"panel panel-default\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<h4 class=\"panel-title\">\r\n");
      out.write("						<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse1\">이용 시 유의사항에 동의</a>\r\n");
      out.write("					</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"collapse1\" class=\"panel-collapse collapse\">\r\n");
      out.write("					<div class=\"panel-body\">\r\n");
      out.write("						- 당일 예약 불가능. 일주일 전부터 예약 가능<br> - 예약 최대 기간은 1개월 이내<br> -\r\n");
      out.write("						예약 변경은 불가 (취소 후 재 예약 가능)<br> - 제품 가격에 맞춰 손해배상 청구<br> <br>\r\n");
      out.write("						- 기본 제공사항<br> - 공용 화장실<br> - 공용 샤워장<br> - 릴선<br>\r\n");
      out.write("						- 코로나19 방역소독\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"terms_of_Use\" value=\"agree\">동의</label>\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"terms_of_Use\" value=\"disagree\" checked>비동의</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"panel panel-default\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<h4 class=\"panel-title\">\r\n");
      out.write("						<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse2\">취소 수수료에 동의</a>\r\n");
      out.write("					</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"collapse2\" class=\"panel-collapse collapse\">\r\n");
      out.write("					<div class=\"panel-body\">\r\n");
      out.write("						- 환불규정<br> - 이용 8일전 수수료 없음<br> - 이용 6~7일전 총 금액의 20% 차감<br>\r\n");
      out.write("						- 이용 5~4일전 총 금액의 30% 차감<br> - 이용 2~3일전 총 금액의 40% 차감<br>\r\n");
      out.write("						- 이용 1일전 총 금액의 50% 차감<br> - 이용 당일 환불 불가\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"cancellation_Fee\" value=\"agree\">동의</label>\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"cancellation_Fee\" value=\"disagree\" checked>비동의</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"panel panel-default\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<h4 class=\"panel-title\">\r\n");
      out.write("						<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse3\">개인정보 수집 및 이용에 동의</a>\r\n");
      out.write("					</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"collapse3\" class=\"panel-collapse collapse\">\r\n");
      out.write("					<div class=\"panel-body\">\r\n");
      out.write("						1.개인정보 수집목적 및 이용목적<br> 가. 서비스 제공에 관한 계약 이행 및 서비스 제공에 따른 요금정산,\r\n");
      out.write("						콘텐츠 제공, 구매 및 요금 결제,<br> 물품배송 또는 청구지 등 발송, 금융거래 본인 인증 및 금융 서비스<br>\r\n");
      out.write("						나. 회원 관리<br> 회원제 서비스 이용에 따른 본인확인, 개인 식별, 불량회원의 부정 이용 방지와 비인가\r\n");
      out.write("						사용 방지,<br> 가입 의사 확인, 연령확인, 만14세 미만 아동 개인정보 수집 시 법정 대리인 동의여부\r\n");
      out.write("						확인, 불만처리 등 민원처리, 고지사항 전달<br> 2.수집하는 개인정보 항목 : 이름, 로그인ID,\r\n");
      out.write("						비밀번호, 주소, 휴대전화번호, 이메일, 14세미만 가입자의 경우 법정대리인의 정보<br> 3.개인정보의\r\n");
      out.write("						보유기간 및 이용기간 원칙적으로, 개인정보 수집 및 이용목적이 달성된 후에는 해당<br> 정보를 지체 없이\r\n");
      out.write("						파기합니다. 단, 다음의 정보에 대해서는 아래의 이유로 명시한 기간 동안 보존.<br> 가. 회사 내부 방침에\r\n");
      out.write("						의한 정보 보유 사유<br> o 부정거래 방지 및 운영방침에 따른 보관 : 5년<br> 나. 관련\r\n");
      out.write("						법령에 의한 정보보유 사유<br> o 계약 또는 청약철회 등에 관한 기록<br> -보존이유 :\r\n");
      out.write("						전자상거래등에서의소비자보호에관한법률<br> -보존기간 : 5년<br> o 대금 결제 및 재화 등의\r\n");
      out.write("						공급에 관한 기록<br> -보존이유: 전자상거래등에서의소비자보호에관한법률<br> -보존기간 : 5년<br>\r\n");
      out.write("						o 소비자 불만 또는 분쟁처리에 관한 기록<br> -보존이유 : 전자상거래등에서의소비자보호에관한법률<br>\r\n");
      out.write("						-보존기간 : 3년<br> ※ 동의를 거부할 수 있으나 거부시 회원 가입이 불가능합니다.\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"Privacy\" value=\"agree\">동의</label>\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"Privacy\" value=\"disagree\" checked>비동의</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"panel panel-default\">\r\n");
      out.write("				<div class=\"panel-heading\">\r\n");
      out.write("					<h4 class=\"panel-title\">\r\n");
      out.write("						<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse4\">이용자가 미성년자가 아니며 성인임에 동의</a>\r\n");
      out.write("					</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"collapse4\" class=\"panel-collapse collapse\">\r\n");
      out.write("					<div class=\"panel-body\">미성년자 입실 혼숙 금지 (관계 법령 의거)</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"adult\" value=\"agree\">동의</label>\r\n");
      out.write("				<label class=\"radio-inline\"> <input type=\"radio\" name=\"adult\" value=\"disagree\" checked>비동의</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"col-sm-12\">\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<h2>업체 계좌번호 및 결제 금액</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"well\" align=\"center\" >\r\n");
      out.write("		<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"left\"><font size=\"4\">계좌번호 : **은행 0000 – 000 – 000000</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"left\"><font size=\"4\">예 금 주 : * * *</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td><font size=\"4\">결제 금액</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td><font size=\"4\">000,000 원</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
